version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  nestjs:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/sgroup
